<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGenus extends sfDoctrineRecord
{
  public function setTableDefinition()
  {
    $this->setTableName('genus');
    $this->hasColumn('id', 'integer', 8, array('type' => 'integer', 'primary' => true, 'autoincrement' => true, 'length' => '8'));
    $this->hasColumn('name', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
    $this->hasColumn('sub_family_id', 'integer', 8, array('type' => 'integer', 'notnull' => true, 'length' => '8'));
    $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'notnull' => true, 'length' => '4'));
    $this->hasColumn('species_count', 'integer', 8, array('type' => 'integer', 'notnull' => true, 'length' => '8'));
    $this->hasColumn('is_published', 'integer', 1, array('type' => 'integer', 'default' => '1', 'notnull' => true, 'length' => '1'));
    $this->hasColumn('first_discovered_at', 'date', 25, array('type' => 'date', 'notnull' => true, 'length' => '25'));
    $this->hasColumn('fun_fact', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('created_at', 'date', 25, array('type' => 'date', 'length' => '25'));
    $this->hasColumn('updated_at', 'date', 25, array('type' => 'date', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('SubFamily', array('local' => 'sub_family_id',
                                     'foreign' => 'id'));

    $this->hasOne('sfGuardUser', array('local' => 'user_id',
                                       'foreign' => 'id'));

    $this->hasMany('GenusNote', array('local' => 'id',
                                      'foreign' => 'genus_id'));
  }
}