default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, all.css, dataTables.bootstrap4.min.css, jquery.dataTables.min.css, main.css, styles.css]

  javascripts:    [jquery-3.4.1.min.js, popper.min.js, bootstrap.min.js, dataTables.bootstrap4.min.js, jquery.dataTables.min.js, all.js, main.js]

  has_layout:     on
  layout:         layout
