<?php
// auto-generated by sfRoutingConfigHandler
// date: 2019/12/17 11:35:55
return array(
'genus' => new sfDoctrineRouteCollection(array (
  'model' => 'Genus',
  'name' => 'genus',
  'requirements' => 
  array (
  ),
)),
'list' => new sfRoute('/genus/list', array (
  'module' => 'genus',
  'action' => 'list',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'genus',
  'action' => 'index',
), array (
), array (
)),
);
