<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/12/17 11:35:57
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
