<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/12/17 11:35:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=192.168.104.250;dbname=teste_jobeet',
  'username' => 'devuser',
  'password' => 'dev!123user',
  'name' => 'doctrine',
)),);
