<?php
// auto-generated by sfRoutingConfigHandler
// date: 2019/12/17 11:35:41
return array(
'sub_family' => new sfDoctrineRouteCollection(array (
  'model' => 'SubFamily',
  'name' => 'sub_family',
  'requirements' => 
  array (
  ),
)),
'list' => new sfRoute('/genus/list', array (
  'module' => 'genus',
  'action' => 'list',
), array (
), array (
)),
'created_note' => new sfDoctrineRoute('/genus/notes.:sf_format', array (
  'module' => 'genus',
  'action' => 'createNotes',
  'sf_format' => 'html',
), array (
  'sf_method' => 'post',
), array (
  'model' => 'Genus',
  'type' => 'object',
)),
'genus' => new sfDoctrineRouteCollection(array (
  'model' => 'Genus',
  'name' => 'genus',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'genus',
  'action' => 'index',
), array (
), array (
)),
);
