<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/12/17 10:21:39
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'super_admin',
  ),
);
